
services:
  frontend:
    build: 
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./debug/frontend/:/debug
  backend:
    build: 
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./debug/backend/:/debug
    depends_on:
      - db
  db:
    build: 
      dockerfile: db/Dockerfile
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - PGDATA=$DB_DATA
