services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
      target: $STAGE
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./debug/frontend/:/debug
    environment:
      - GID=$USER_GID
      - HTTP_METHOD=https
      - HOST_NAME=10.12.1.4
      - REACT_APP_CLIENT_ID=${CLIENT_ID}
      - REACT_APP_PORT=443
      - REACT_APP_REDIRECT_URI=https://10.12.1.4
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
      target: $STAGE
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./debug/backend/:/debug
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - GID=$USER_GID
      - DJANGO_SUPERUSER_PASSWORD=$DJANGO_PASS
      - DJANGO_SUPERUSER_EMAIL=$DJANGO_EMAIL
      - DJANGO_SUPERUSER_USERNAME=$DJANGO_USERNAME
      - CLIENT_ID=${CLIENT_ID}
      - REACT_PORT=443
      - HOST_NAME=10.12.1.4
      - HTTP_METHOD=https

  db:
    build: 
      context: db
      dockerfile: Dockerfile
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - PGDATA=$DB_DATA
    healthcheck:
      test: pg_isready -d app -U user -h db -p 5432
      interval: 5s
      retries: 3