
services:
  frontend:
    build: 
      dockerfile: frontend/Dockerfile
      target: $STAGE
    container_name: frontend
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./debug/frontend/:/debug
    environment:
      - GID=$USER_GID
  backend:
    build: 
      dockerfile: backend/Dockerfile
      target: $STAGE
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./debug/backend/:/debug
    depends_on:
      - db
    environment:
      - GID=$USER_GID
      - DJANGO_SUPERUSER_PASSWORD=$DJANGO_PASS
      - DJANGO_SUPERUSER_EMAIL=$DJANGO_EMAIL
      - DJANGO_SUPERUSER_USERNAME=$DJANGO_USERNAME
  db:
    build: 
      dockerfile: db/Dockerfile
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - PGDATA=$DB_DATA
