#!/bin/bash

function handle_ctrlc() {
    echo
    if [[ $ctrlc_received == 0 ]]; then
        echo "Signal received. Press Ctrl+C again to stop!"
        cp -R debug/frontend/src/* frontend/src/.
        cp -R debug/backend/* backend/.
        ctrlc_received=1
    else
        cp -R debug/frontend/src/* frontend/src/.
        cp -R debug/backend/* backend/.
        rm -rf debug
        echo "Debug files copied successfully!"
        exit
    fi
}

main() {
    if [[ "$1" == "development" ]]; then
        mkdir -p debug
    fi

    # Trapping the SIGINT signal
    trap handle_ctrlc SIGINT

    export USER_GID=$(id -g)
    export STAGE=$1

    shift  # Remove the first argument (stage)
    docker-compose up --build "$@"
}

cleanup() {
    docker network prune -f
    rm -rf debug/
    docker rm postgresql 2>/dev/null
    docker kill $(docker ps --format '{{.ID}}') 2>/dev/null
    docker rm $(docker ps -a --format '{{.ID}}') 2>/dev/null
    docker rmi $(docker images --format '{{.ID}}') 2>/dev/null
    docker system prune -af --volumes 2>/dev/null
    rm -rf debug/
}

if [[ "$1" == "production" || "$1" == "development" ]]; then
    main "$@"
elif [[ "$1" == "cleanup" ]]; then
    cleanup
else
    echo "Usage: $0 {production|development|cleanup} [additional docker-compose args]"
    exit 1
fi
